import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { signout } from '@/app/login/actions'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export function SignOutButton() {
  return (
    <form>
      <button formAction={signout}>Sign out</button>
    </form>
  )
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Big_Shoulders, Work_Sans } from 'next/font/google'

const bigShoulders = Big_Shoulders({
  subsets: ['latin'],
  variable: '--font-display',
  weight: ['600', '700', '800'],
  fallback: ['system-ui', 'sans-serif']
})

const workSans = Work_Sans({
  subsets: ['latin'],
  variable: '--font-body',
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${bigShoulders.variable} ${workSans.variable}`}>
      <body>{children}</body>
    </html>
  )
}